# Generated by Django 4.0.3 on 2022-04-02 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('song', models.CharField(default='SOME STRING', max_length=200, primary_key=True, serialize=False)),
                ('average_rating', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('artist_name', models.CharField(default='SOME STRING', max_length=200, primary_key=True, serialize=False)),
                ('album', models.CharField(default='SOME STRING', max_length=200)),
                ('genre', models.CharField(default='SOME STRING', max_length=200)),
                ('year', models.IntegerField(default=2000)),
                ('record_company', models.CharField(default='SOME STRING', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(default='SOME STRING', max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(default='SOME STRING', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1)),
                ('song', models.ForeignKey(default='SOME STRINGS', max_length=200, on_delete=django.db.models.deletion.CASCADE, to='MusicApp.artist')),
                ('username', models.ForeignKey(default='SOME STRING', max_length=200, on_delete=django.db.models.deletion.CASCADE, to='MusicApp.user')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='artist',
            field=models.ForeignKey(default='SOME STRING', max_length=200, on_delete=django.db.models.deletion.CASCADE, to='MusicApp.attribute'),
        ),
    ]
